sudo: required

services:
  - docker

language: go

go:
  - 1.16.x
  - tip

script: make test
 
after_success:
  — sh .travis/dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/heroku.sh
